let  potions = [
    {name: "Felix Felicis",
        recipe: ["a lacewing fly", "beetle eyes", "a drop of dragon blood", "boomslang skin", "beetle eyes", "boomslang skin",], 
        insult: "A cauldron full of liquid luck still wouldn't be enough to help you pass your potions final."},
    {name: "Draught of Living Death", 
        recipe: ["powdered bicorn horn", "an eye of newt", "boomslang skin", "beetle eyes", "an eye of newt",], 
        insult: "Work faster or I'll be forced to feed a drop of this to your owl."},
    {name: "Polyjuice", 
        recipe: ["boomslang skin", "a lacewing fly", "powdered bicorn horn", "an eye of newt", "a drop of dragon blood", "powdered bicorn horn"], 
        insult: "Being anyone else is surely better than being you."},
    {name: "Veritaserum", 
        recipe: ["beetle eyes", "powdered bicorn horn", "an eye of newt", "beetle eyes", "a drop of dragon blood",], 
        insult: "Maybe we'll test this one on you and see who really put troll bogeys on my shoes."},
    {name: "Amortentia", 
        recipe: ["boomslang skin", "a lacewing fly", "beetle eyes", "a lacewing fly", "powdered bicorn horn", "beetle eyes"], 
        insult: "Brew this one right and you might actually get someone to tolerate you."},
    {name: "Pepperup", 
        recipe: ["beetle eyes", "powdered bicorn horn", "a lacewing fly", "an eye of newt", "a drop of dragon blood"], 
        insult: "I'm sick of seeing your face in my class, maybe this potion will help."},
    {name: "Confusion", 
        recipe: ["powdered bicorn horn", "a lacewing fly", "a drop of dragon blood", "beetle eyes", "an eye of newt"], 
        insult: "Careful with this one, you can't afford to be more confused."},
    {name: "Invisibility", 
        recipe: ["an eye of newt", "a lacewing fly", "powdered bicorn horn", "boomslang skin", "a drop of dragon blood"], 
        insult: "Rub some of this on your face so I don't have to look at it anymore"},
    {name: "Ageing",
        recipe: ["a lacewing fly", "a drop of dragon blood", "an eye of newt", "beetle eyes", "powdered bicorn horn"],
        insult: "I can already tell you won't age gracefully."},
    {name: "Babbling Beverage",
        recipe: ["a drop of dragon blood", "beetle eyes", "powdered bicorn horn", "a drop of dragon blood", "an eye of newt",],
        insult: "Do not test this potion, you spout enough nonsense already."},
    {name: "Calming Draught",
        recipe: ["boomslang skin", "an eye of newt", "beetle eyes", "boomslang skin", "an eye of newt",],
        insult: "Dumbledore still refuses to let me add this to our student's pumpkin juice."},
    {name: "Dragon Tonic",
        recipe: ["an eye of newt", "powdered bicorn horn", "beetle eyes", "a drop of dragon blood", "an eye of newt", "powdered bicorn horn", "a lacewing fly"],
        insult: "Maybe we'll let you give this to the dragon yourself and maybe you won't come back."},
    {name: "Rat Tonic",
        recipe: ["a drop of dragon blood","a lacewing fly", "beetle eyes", "powdered bicorn horn", "an eye of newt"],
        insult: "This works on other vermin, you for example."},
    {name: "Cure for Boils",
        recipe: ["powdered bicorn horn", "a drop of dragon blood", "an eye of newt", "a lacewing fly", "powdered bicorn horn"],
        insult: "There will be no silly wand waving or foolish incantations in this class!"},
  ]

export default potions;